language: python
python:
    - 3.7
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-test.txt"
jobs:
  include:
    - stage: all
      script: ./test.sh
cache: pip
