"""drop columns

Revision ID: 0943360f38b0
Revises: 5b9405ee499c
Create Date: 2019-12-18 20:14:11.400011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0943360f38b0'
down_revision = '5b9405ee499c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
