"""add facebook

Revision ID: 0baf7ff8cd30
Revises: 3a51544b7df6
Create Date: 2019-12-08 22:26:03.209693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0baf7ff8cd30'
down_revision = '3a51544b7df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
