"""empty message

Revision ID: 16551a8bebea
Revises: d9e93185b980
Create Date: 2019-11-23 21:07:05.861609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16551a8bebea'
down_revision = 'd9e93185b980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
