"""empty message

Revision ID: 181269cb118b
Revises: fdc419aea959
Create Date: 2019-11-01 00:23:33.616788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181269cb118b'
down_revision = 'fdc419aea959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(length=127), nullable=False))
    op.add_column('events', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('time', sa.DateTime(), nullable=False))
    op.drop_column('events', 'location_name')
    op.drop_column('events', 'location_lon')
    op.drop_column('events', 'time_start')
    op.drop_column('events', 'venmo')
    op.drop_column('events', 'location_lat')
    op.drop_column('events', 'time_end')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=127), nullable=True))
    op.add_column('events', sa.Column('time_end', sa.DATETIME(), nullable=True))
    op.add_column('events', sa.Column('location_lat', sa.FLOAT(), nullable=True))
    op.add_column('events', sa.Column('venmo', sa.VARCHAR(length=32), nullable=True))
    op.add_column('events', sa.Column('time_start', sa.DATETIME(), nullable=False))
    op.add_column('events', sa.Column('location_lon', sa.FLOAT(), nullable=True))
    op.add_column('events', sa.Column('location_name', sa.VARCHAR(length=127), nullable=False))
    op.drop_column('events', 'time')
    op.drop_column('events', 'lon')
    op.drop_column('events', 'location')
    op.drop_column('events', 'lat')
    # ### end Alembic commands ###
