"""empty message

Revision ID: 1dd194c79815
Revises: f01b1804fdfd
Create Date: 2019-12-18 18:33:20.114244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd194c79815'
down_revision = 'f01b1804fdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Boolean(), nullable=True),
    sa.Column('negative', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('positive', sa.BOOLEAN(), nullable=True),
    sa.Column('negative', sa.BOOLEAN(), nullable=True),
    sa.Column('review', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('negative IN (0, 1)'),
    sa.CheckConstraint('positive IN (0, 1)'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
