"""empty message

Revision ID: 233aa618e50b
Revises: c7194142131c
Create Date: 2019-11-13 22:24:06.742557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233aa618e50b'
down_revision = 'c7194142131c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('confirmed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'confirmed')
    # ### end Alembic commands ###
