"""convert invitations to full model

Revision ID: 34abab524653
Revises: 48fe4a675716
Create Date: 2022-04-09 17:13:31.275203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34abab524653'
down_revision = '48fe4a675716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'id')
    # ### end Alembic commands ###
