"""event_images

Revision ID: 48fe4a675716
Revises: 50e6e779158c
Create Date: 2020-08-30 11:51:34.283748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fe4a675716'
down_revision = '50e6e779158c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image')
    # ### end Alembic commands ###
