"""empty message

Revision ID: 4bb64fd6de2c
Revises: 7acb6993964c
Create Date: 2019-11-26 10:24:18.909329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb64fd6de2c'
down_revision = '7acb6993964c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'capacity')
    # ### end Alembic commands ###
