"""add alcohol column

Revision ID: 50e6e779158c
Revises: ee349923153a
Create Date: 2020-01-12 01:50:19.987755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e6e779158c'
down_revision = 'ee349923153a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('alcohol', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'alcohol')
    # ### end Alembic commands ###
