"""empty message

Revision ID: 677035c93a44
Revises: 16551a8bebea
Create Date: 2019-11-26 00:14:31.261110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677035c93a44'
down_revision = '16551a8bebea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('open', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('transitive_invites', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'transitive_invites')
    op.drop_column('events', 'open')
    # ### end Alembic commands ###
