"""add updates

Revision ID: 877cf9d3c666
Revises: 0943360f38b0
Create Date: 2020-01-01 09:37:42.615570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877cf9d3c666'
down_revision = '0943360f38b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lng')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('lng', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
