"""empty message

Revision ID: b4b0d2bd8d4c
Revises: f61505a70b4b
Create Date: 2019-11-03 23:38:18.950483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b0d2bd8d4c'
down_revision = 'f61505a70b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id_from', sa.Integer(), nullable=False),
    sa.Column('user_id_to', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id_from', 'user_id_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
