"""Add venmo

Revision ID: ee349923153a
Revises: 6d04ec634fd9
Create Date: 2020-01-11 16:25:32.253929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee349923153a'
down_revision = '6d04ec634fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venmo', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'venmo')
    # ### end Alembic commands ###
