"""add year

Revision ID: f01b1804fdfd
Revises: 5c6026965ef1
Create Date: 2019-12-16 17:22:27.402848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01b1804fdfd'
down_revision = '5c6026965ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year')
    # ### end Alembic commands ###
