"""Add facebook_name

Revision ID: fb4e8e2b7a16
Revises: 0baf7ff8cd30
Create Date: 2019-12-08 22:50:49.822130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4e8e2b7a16'
down_revision = '0baf7ff8cd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_name')
    # ### end Alembic commands ###
